version: '3.8'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    environment:
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=database
    depends_on:
      - db

  db:
    build: ./docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=friedrich
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:   
